# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
#
# Header content for the release notes page. The managed `make.jl` prepends
# this to the project-root NEWS.md when both exist.

const RELEASE_NOTES_HEADER = """
```@meta
EditURL = "https://github.com/seabbs/MultiHubForecaster.jl/blob/main/NEWS.md"
```

# Release notes

MultiHubForecaster.jl follows a hybrid changelog approach:
- **GitHub Releases**: All releases (automatically generated by TagBot)
- **NEWS.md**: Major releases requiring detailed context (shown below)

See [GitHub Releases](https://github.com/seabbs/MultiHubForecaster.jl/releases) for minor/patch
release information.

"""
